descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/client/CirculationClient.java
src/main/java/org/folio/controller/EcsTlrController.java
src/main/java/org/folio/domain/entity/EcsTlrEntity.java
src/main/java/org/folio/domain/mapper/EcsTlrMapper.java
src/main/java/org/folio/exception/TenantScopedExecutionException.java
src/main/java/org/folio/service/EcsTlrService.java
src/main/java/org/folio/service/TenantScopedExecutionService.java
src/main/java/org/folio/service/impl/EcsTlrServiceImpl.java
src/main/java/org/folio/service/impl/TenantScopedExecutionServiceImpl.java
src/main/resources/application.yml
src/main/resources/db/changelog/changes/initial_schema.xml
src/main/resources/log4j2.properties
src/main/resources/swagger.api/ecs-tlr.yaml
src/main/resources/swagger.api/schemas/EcsTlr.yaml
src/main/resources/swagger.api/schemas/override-blocks.json
src/main/resources/swagger.api/schemas/request-search-index.json
src/main/resources/swagger.api/schemas/request.json
src/main/resources/swagger.api/schemas/tags.json
src/main/resources/swagger.api/schemas/uuid.json
src/test/java/org/folio/api/BaseIT.java
src/test/java/org/folio/api/EcsTlrApiTest.java
src/test/java/org/folio/controller/EcsTlrControllerTest.java
src/test/java/org/folio/controller/KafkaEventListenerTest.java
src/test/java/org/folio/service/EcsTlrServiceTest.java
src/test/java/org/folio/service/TenantScopedExecutionServiceTest.java

Add Circulation client able to create requests in a different tenant.
Replace value of header `X-Okapi-Tenant` in outgoing POST-requests to `/circulation/request` with ID of target tenant.

MODTLR-10: Support for cross-tenant requests

---

src/main/java/org/folio/domain/strategy/ItemStatusBasedTenantPickingStrategy.java
src/main/java/org/folio/domain/strategy/TenantPickingStrategy.java
src/main/java/org/folio/exception/RequestCreatingException.java
src/main/java/org/folio/service/impl/EcsTlrServiceImpl.java
src/test/java/org/folio/domain/strategy/ItemStatusBasedTenantPickingStrategyTest.java
src/test/java/org/folio/service/EcsTlrServiceTest.java

MODTLR-11 creates a secondary TLR in the data tenant (lending side).
In scope of this ticket:
In case of a failure, select the next tenant using the same priority described in MODTLR-11.
Attempt to create a TLR in the selected tenant.
Repeat until TLR is successfully created or until there are no more tenants.
Resolves: [MODTLR-18](https://folio-org.atlassian.net/browse/MODTLR-18)

[MODTLR-18] Implement retry creation on failure

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/client/feign/UserClient.java
src/main/java/org/folio/service/UserService.java
src/main/java/org/folio/service/impl/RequestServiceImpl.java
src/main/java/org/folio/service/impl/UserCloningServiceImpl.java
src/main/java/org/folio/service/impl/UserServiceImpl.java
src/main/resources/permissions/mod-tlr.csv
src/main/resources/swagger.api/schemas/user.json
src/test/java/org/folio/api/EcsTlrApiTest.java

Covers: [MODTLR-27](https://folio-org.atlassian.net/browse/MODTLR-27) 
Before placing a request in the data tenant, mod-tlr creates a requester copy in that tenant. This copy should contain only
required fields: UUID, barcode, patron group

MODTLR-27 Remove unneeded fields from the requester copy, update group

---

Dockerfile

Run apk upgrade in the Dockerfile as recommended in
https://github.com/folio-org/folio-tools/tree/master/folio-java-docker/openjdk17#sample-module-dockerfile 
[MODTLR-36](https://folio-org.atlassian.net/browse/MODTLR-36)

MODTLR-36: Upgrade packages in Dockerfile

---

src/main/java/org/folio/client/feign/CirculationClient.java
src/main/java/org/folio/controller/AllowedServicePointsController.java
src/main/java/org/folio/service/impl/AllowedServicePointsServiceImpl.java
src/main/resources/swagger.api/allowed-service-points.yaml
src/test/java/org/folio/api/AllowedServicePointsApiTest.java

Covers: [MODTLR-50](https://folio-org.atlassian.net/browse/MODTLR-50)
Use patronGroupId parameter instead of requesterId

[MODTLR-50] Use patronGroupId parameter instead of requesterId

---

pom.xml
src/main/resources/swagger.api/schemas/userGroup.json
src/main/resources/swagger.api/schemas/userTenant.json
src/main/resources/swagger.api/schemas/userTenantCollection.json

Add additionalProperties: true to UserGroup, UserTenant, UserTenantCollection schemas. Some tests will fail.
Updated openapi generator plugin version
[MODTLR-52](https://folio-org.atlassian.net/browse/MODTLR-52)

MODTLR-52 switch additionalProperties to true to defined schemas

---

src/main/java/org/folio/domain/mapper/EcsTlrMapper.java
src/main/java/org/folio/service/DcbService.java
src/main/java/org/folio/service/TenantService.java
src/main/java/org/folio/service/impl/DcbServiceImpl.java
src/main/java/org/folio/service/impl/EcsTlrServiceImpl.java
src/main/java/org/folio/service/impl/TenantServiceImpl.java
src/test/java/org/folio/api/EcsTlrApiTest.java
src/test/java/org/folio/service/EcsTlrServiceTest.java
src/test/java/org/folio/service/TenantServiceTest.java

Currently, DCB transactions are created upon secondary request update and only for TLR hold requests. They should also be created for all other request type and level combinations immediately when ECS TLR is created.
[MODTLR-51](https://folio-org.atlassian.net/browse/MODTLR-51)

MODTLR-51: Create DCB transactions immediately when ECS TLR is created

---

src/main/java/org/folio/domain/entity/EcsTlrEntity.java
src/main/java/org/folio/service/impl/EcsTlrServiceImpl.java
src/test/java/org/folio/api/EcsTlrApiTest.java
src/test/java/org/folio/controller/KafkaEventListenerTest.java

When ECS TLR POST request comes without an id, mod-tlr needs to generate one
[MODTLR-53](https://folio-org.atlassian.net/browse/MODTLR-53)

MODTLR-53 Autogenerate UUID for ECS TLR when client doesn't provide it

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/client/feign/CirculationClient.java
src/main/java/org/folio/controller/AllowedServicePointsController.java
src/main/java/org/folio/domain/Constants.java
src/main/java/org/folio/domain/dto/AllowedServicePointsRequest.java
src/main/java/org/folio/domain/dto/RequestOperation.java
src/main/java/org/folio/listener/kafka/KafkaEventListener.java
src/main/java/org/folio/repository/EcsTlrRepository.java
src/main/java/org/folio/service/AllowedServicePointsService.java
src/main/java/org/folio/service/RequestService.java
src/main/java/org/folio/service/impl/AllowedServicePointsServiceImpl.java
src/main/java/org/folio/service/impl/EcsTlrServiceImpl.java
src/main/java/org/folio/service/impl/RequestServiceImpl.java
src/main/resources/swagger.api/allowed-service-points.yaml
src/test/java/org/folio/api/AllowedServicePointsApiTest.java

Add support for operation `replace` in Allowed Service Points API.
[MODTLR-56](https://folio-org.atlassian.net/browse/MODTLR-56)

MODTLR-56: Support for operation `replace` in Allowed Service Points API

---

src/main/java/org/folio/client/feign/RequestCirculationClient.java
src/main/java/org/folio/service/RequestService.java
src/main/java/org/folio/service/impl/RequestBatchUpdateEventHandler.java
src/main/java/org/folio/service/impl/RequestServiceImpl.java
src/main/resources/permissions/mod-tlr.csv
src/main/resources/swagger.api/ecs-tlr.yaml
src/main/resources/swagger.api/schemas/reorder-queue.json
src/test/java/org/folio/service/RequestBatchUpdateEventHandlerTest.java

Handle Kafka event generated on request update.
When updated request is a primary request (ecsRequestPhase=Primary) and its position updated, secondary request should also be updated.
Load the queue of the primary request (TLR is enabled, it should be a unified queue - all requests with the same instanceId)
Find primary requests in this queue and get their corresponding secondary requests.
Load all request queues for all of the secondary requests (again, unified queues because TLR should always be enabled in data tenants in Phase I). There could be multiple such queues because secondary requests could be located in different tenants.
For each of the secondary request queues:
Check if secondary requests in the queue have the same order (not necessarily same positions) as their …

[MODTLR-43] Reorder secondary requests in sync with primary requests [Part 2]

---

src/main/java/org/folio/service/impl/RequestBatchUpdateEventHandler.java
src/main/java/org/folio/util/HttpUtils.java
src/test/java/org/folio/api/EcsTlrApiTest.java
src/test/java/org/folio/util/HttpUtilsTest.java

When creating an ECS TLR, mod-tlr determines borrowing tenant ID by extracting it from the token stored in the request cookies. But when the request is made using a system user (provided by folio-spring-system-user library), the token is always moved from cookies to “x-okapi-token” header. So when we can’t find the token in the cookies, we need to look in the headers as well.
[MODTLR-67](https://folio-org.atlassian.net/browse/MODTLR-67)

MODTLR-67: Get token from headers as a fallback

---

src/main/java/org/folio/client/feign/CirculationClient.java
src/main/java/org/folio/controller/AllowedServicePointsController.java
src/main/java/org/folio/service/impl/AllowedServicePointsForItemLevelRequestService.java
src/main/java/org/folio/service/impl/AllowedServicePointsForTitleLevelRequestService.java
src/main/java/org/folio/service/impl/AllowedServicePointsServiceImpl.java
src/test/java/org/folio/api/AllowedServicePointsApiTest.java

https://folio-org.atlassian.net/browse/MODTLR-68
1. Updated existing implementation to remove checks based on routing service points.
2. Used approach to fetch all valid service points in corresponding tenants.

MODTLR-68: Allowed service points - only use lending side circulation rules

---

descriptors/ModuleDescriptor-template.json

MODTLR-97
Use new permission names from mod-circulation

MODTLR-97 Rename mod-settings permissions

---

src/main/java/org/folio/service/impl/UserCloningServiceImpl.java
src/test/java/org/folio/service/UserCloningServiceTest.java

MODTLR-116 
If patron name is Secure Patron, keep it when cloning the requester to other tenants

MODTLR-116 Copy Secure Patron name when cloning users

---

src/main/java/org/folio/listener/kafka/KafkaEventListener.java
src/main/java/org/folio/repository/EcsTlrRepository.java
src/main/java/org/folio/service/DcbService.java
src/main/java/org/folio/service/impl/DcbServiceImpl.java
src/main/java/org/folio/service/impl/LoanEventHandler.java
src/main/java/org/folio/service/impl/RequestEventHandler.java
src/main/resources/swagger.api/ecs-tlr.yaml
src/main/resources/swagger.api/schemas/loan.json
src/test/java/org/folio/listener/KafkaEventListenerTest.java
src/test/java/org/folio/service/DcbServiceTest.java
src/test/java/org/folio/service/LoanEventHandlerTest.java

[MODTLR-112](https://folio-org.atlassian.net/browse/MODTLR-112)

MODTLR-112: DCB transaction status synchronization

---

pom.xml

https://folio-org.atlassian.net/browse/MODTLR-125
Fix security vulnerabilities in dependencies.
Upgrade Spring Boot from 3.3.0 to 3.3.7.
Upgrade folio-spring-* from 8.2.0 to 8.2.2.
These upgrades indirectly upgrade kafka-clients from 3.7.0 to 3.7.2 fixing
* https://www.cve.org/CVERecord?id=CVE-2024-56128 Incorrect Implementation of Authentication Algorithm
These upgrades indirectly upgrade tomcat-embed-core from 10.1.24 to 10.1.34 fixing
* https://www.cve.org/CVERecord?id=CVE-2024-38286 Allocation of Resources Without Limits or Throttling
* https://www.cve.org/CVERecord?id=CVE-2024-34750 Insufficient Session Expiration
These upgrades indirectly upgrade spring-security-crypto from 6.3.0 to 6.3.6 fixing
* https://www.cve.org/CVERecord?id=CVE-2024-38827 Authorization Bypass

MODTLR-125: Spring Boot 3.3.7, folio-spring 8.2.2 fixing vulns

---

src/main/java/org/folio/service/impl/EcsTlrServiceImpl.java
src/test/java/org/folio/api/EcsTlrApiTest.java

Problem: The Patron Comments for ECS requests do not display in Primary requests. They do display in Secondary requests in the Requests app
Resolves: [MODTLR-139](https://folio-org.atlassian.net/browse/MODTLR-139)

MODTLR-139 Add patronComments mapping to primary request

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml

Add workflow_dispatch, needed for https://folio-org.atlassian.net/browse/FOLIO-4183
This keeps the *.yml files in sync with the templates: https://github.com/folio-org/.github/tree/master/workflow-templates
Update the .github/workflows/*.yml files.

Add workflow_dispatch to api workflows

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/client/feign/CheckOutClient.java
src/main/java/org/folio/client/feign/CirculationClient.java
src/main/java/org/folio/client/feign/LoanPolicyClient.java
src/main/java/org/folio/domain/mapper/CheckOutDryRunRequestMapper.java
src/main/java/org/folio/service/LoanPolicyService.java
src/main/java/org/folio/service/impl/CheckOutServiceImpl.java
src/main/java/org/folio/service/impl/LoanPolicyCloningServiceImpl.java
src/main/java/org/folio/service/impl/LoanPolicyServiceImpl.java
src/main/resources/permissions/mod-tlr.csv
src/main/resources/swagger.api/ecs-loans.yaml
src/main/resources/swagger.api/schemas/circulation-storage/loan-policy.json
src/main/resources/swagger.api/schemas/circulation-storage/period.json
src/main/resources/swagger.api/schemas/circulation/check-out-dry-run-request.yaml
src/main/resources/swagger.api/schemas/circulation/check-out-dry-run-response.yaml
src/main/resources/swagger.api/schemas/circulation/check-out-request.yaml
src/test/java/org/folio/api/CheckOutApiTest.java

New endpoint GET /tlr/loans/check-out-by-barcode, in addition to what’s implemented in https://folio-org.atlassian.net/browse/MODTLR-151, needs to:
Call check out dry run mod-circulation in that data tenant to define a loan policy to be copied (dependency - https://folio-org.atlassian.net/browse/CIRC-2266)
Call mod-circulation-storage in that data tenant to retrieve a loan policy by UUID
Call mod-circulation-storage in the Central tenant to store loan policy in Central tenant’s mod-circulation-storage
Same UUID
Add prefix to the loan policy name to highlight it’s a copy (CLONE_ ?)
Call mod-circulation to perform check out and force cloned policy (dependency - https://folio-org.atlassian.net/browse/CIRC-2267)
Resolves: [MODTLR-152](https://folio-org.atlassian.net/browse/MODTLR-152)

MODTLR-152 Add force loan policy support during check-out

---

descriptors/ModuleDescriptor-template.json

Increase module's memory allocation to 1gb to try and fix module's failure during platform-complete builds.
[MODTLR-176](https://folio-org.atlassian.net/browse/MODTLR-176)

MODTLR-176: Increase memory allocation

---

src/main/java/org/folio/service/impl/RequestServiceImpl.java
src/test/java/org/folio/service/RequestServiceTest.java

Problem: When attempting to place an ILR Hold on an Item that is already Paged, User receives a error message "This request was not placed successfully".
Preconditions:
A Page was already created for this Item.
Steps to reproduce:
From the Central tenant:
Place an ILR on an available Item (e.g., onsite general collections)
Immediately place a Hold on that same Item for a different User
Expected result: ECS Request created
Actual result: User gets an error; Secondary request is created
Resolves: [MODTLR-162](https://folio-org.atlassian.net/browse/MODTLR-162)

MODTLR-162 Fix issue with creating ECS request for Paged item

---

src/main/java/org/folio/listener/kafka/KafkaEventListener.java
src/main/java/org/folio/service/impl/RequestEventHandler.java
src/main/java/org/folio/support/KafkaEvent.java
src/test/java/org/folio/listener/KafkaEventListenerTest.java
src/test/java/org/folio/service/LoanEventHandlerTest.java
src/test/java/org/folio/service/RequestEventHandlerTest.java

https://folio-org.atlassian.net/browse/MODTLR-164
Propagate CLOSED_CANCELED status change on secondary request when request does not contain itemId so DCB will not handle status update.

MODTLR-164: Secondary request (TLR Hold) not canceled after primary request was cancelled

---

src/main/resources/swagger.api/schemas/request.json

`RequestBatchUpdateEventHandler` deserializes requests in the request queue using mod-circulatin-storage's schema, while these requests are built according to mod-circulation's extended request schema. Currently, deserialization of such requets fails, because 
mod-tlr expects property `patronGroup` to be a string (according to mod-circulation-storage schema), while in fact is is an object (according to mod-circulation's request schema). 
https://folio-org.atlassian.net/browse/MODTLR-150
Ideally, we need to use mod-circulation's request schema to deserialize request queue, but a much quicker and easier solution is to just remove patron group from the existing schema.

MODTLR-150: Remove `patronGroup` from request schema
