.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, src/main/resources/swagger.api/title-level-requests.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
=> FOLIO-3678 MODTLR-2 Use GitHub Workflows api-lint and api-schema-lint and api-doc

PERSONAL_DATA_DISCLOSURE.md, README.md
Add PERSONAL_DATA_DISCLOSURE.md form
Also, add a link to the issue tracker
Doc: https://dev.folio.org/guidelines/create-new-repo
Jira ticket: https://issues.folio.org/browse/MODTLR-3
=> MODTLR-3 Add PD disclosure form

src/main/java/org/folio/domain/mapper/EcsTlrMapper.java, src/main/resources/swagger.api/schemas/EcsTlr.yaml
Fix mapping issue from DTO to entity
Resolves: [MODTLR-5](https://issues.folio.org/browse/MODTLR-5)
=> [MODTLR-5] Fix mapping from dto to entity

README.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/controller/EcsTlrController.java, src/main/java/org/folio/service/EcsTlrService.java, src/main/java/org/folio/service/impl/EcsTlrServiceImpl.java, src/main/resources/swagger.api/ecs-tlr.yaml, src/main/resources/swagger.api/examples/EcsTlr.sample, src/main/resources/swagger.api/schemas/EcsTlr.yaml, src/test/java/org/folio/controller/EcsTlrControllerTest.java, src/test/java/org/folio/service/EcsTlrServiceTest.java
Create PUT, DELETE endpoints for updating ECS TLRs
Resolves: [MODTLR-9](https://issues.folio.org/browse/MODTLR-9)
=> [MODTLR-9] Create PUT, DELETE endpoints for updating ECS TLRs

descriptors/ModuleDescriptor-template.json
Resolves: [MODTLR-9](https://issues.folio.org/browse/MODTLR-9)
=> [MODTLR-9] fix permissions

descriptors/ModuleDescriptor-template.json
[MODTLR-28](https://folio-org.atlassian.net/browse/MODTLR-28)
=> MODTLR-28 Add missing permissions to Tenant API definition

src/main/java/org/folio/controller/TlrSettingsController.java, src/main/resources/swagger.api/tlr-settings.yaml
Resolves: [MODTLR-24](https://folio-org.atlassian.net/browse/MODTLR-24)
=> [MODTLR-24] Update content type for PUT endpoint

descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODTLR-33 Add missing interface dependencies
Add missing dependencies to the module descriptor
=> MODTLR-33 Add missing dependencies

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/client/feign/CirculationClient.java, src/main/java/org/folio/controller/AllowedServicePointsController.java, src/main/java/org/folio/service/AllowedServicePointsService.java, src/main/java/org/folio/service/impl/AllowedServicePointsServiceImpl.java, src/main/java/org/folio/service/impl/RequestServiceImpl.java, src/main/resources/swagger.api/allowed-service-points.yaml, src/main/resources/swagger.api/schemas/allowedServicePoints.yaml, src/main/resources/swagger.api/schemas/allowedServicePointsResponse.yaml, src/test/java/org/folio/api/AllowedServicePointsApiTest.java
[MODTLR-25](https://folio-org.atlassian.net/browse/MODTLR-25)
Add new interface, endpoint.
=> MODTLR-25 Create allowed-service-points endpoint

descriptors/ModuleDescriptor-template.json
MODTLR-25 Add permission set
Update module descriptor
=> MODTLR-25 Add permission set

src/main/java/org/folio/service/impl/DcbServiceImpl.java, src/test/java/org/folio/controller/KafkaEventListenerTest.java
Create borrowing DCB-transaction when secondary request is linked to an item.
=> MODTLR-47: Create borrowing DCB-transaction

src/main/resources/permissions/mod-tlr.csv
[MODTLR-49](https://folio-org.atlassian.net/browse/MODTLR-49)
=> MODTLR-49 Add allow-service-points permission to the system user

src/main/java/org/folio/service/DcbService.java, src/main/java/org/folio/service/impl/DcbServiceImpl.java, src/main/java/org/folio/service/impl/RequestEventHandler.java, src/test/java/org/folio/controller/KafkaEventListenerTest.java, src/test/java/org/folio/service/RequestEventHandlerTest.java
Covers: [MODTLR-47](https://folio-org.atlassian.net/browse/MODTLR-47)
Create borrowing transaction in mod-dcb
=> [MODTLR-47] Create borrowing transaction in mod-dcb 

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/resources/application.yml, src/test/java/org/folio/EcsTlrApplicationTest.java
Update folio-spring-support version to enable "Disable system user" feature
[MODTLR-71](https://folio-org.atlassian.net/browse/MODTLR-71)
=> MODTLR-71 Update folio-spring-support version

src/main/resources/permissions/mod-tlr.csv
=> add missed permission

pom.xml, src/test/java/org/folio/EcsTlrApplicationTest.java
Migrate from Spring Boot 3.1 to 3.3
Update dependencies' versions, fix conflicts.
=> MODTLR-37: Upgrade to Spring Boot 3.3.0

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/listener/kafka/KafkaEventListener.java, src/test/java/org/folio/listener/KafkaEventListenerTest.java
=> MODTLR-69 Handle exceptions in Kafka listener

src/main/java/org/folio/service/impl/RequestServiceImpl.java, src/test/java/org/folio/service/RequestServiceTest.java
MODTLR-84 
Do not try to update circulation item when it is null
=> MODTLR-84 Handle null circulation item correctly

descriptors/ModuleDescriptor-template.json
MODTLR-99
Use native mod-settings permissions
=> MODTLR-99 Revert mod-settings perms

descriptors/ModuleDescriptor-template.json
MODTLR-104 
Add mod-settings perms to system user
=> MODTLR-104 Add mod-settings perms to system user

src/main/java/org/folio/controller/AllowedServicePointsController.java, src/main/java/org/folio/domain/dto/AllowedServicePointsRequest.java, src/main/java/org/folio/service/impl/AllowedServicePointsServiceImpl.java, src/main/resources/swagger.api/allowed-service-points.yaml
https://folio-org.atlassian.net/browse/MODTLR-102
Update endpoint to accept patron group
=> MODTLR-102: Allowed SP - accept patronGroupId parameter

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/resources/permissions/mod-tlr.csv
Resolves: [MODTLR-124](https://folio-org.atlassian.net/browse/MODTLR-124)
=> MODTLR-124 Release v1.0.4

NEWS.md, pom.xml
Resolves: [MODTLR-129](https://folio-org.atlassian.net/browse/MODTLR-129)
=> MODTLR-129 Release v1.0.5

src/main/java/org/folio/service/impl/RequestEventHandler.java, src/main/java/org/folio/support/Constants.java, src/test/java/org/folio/service/RequestEventHandlerTest.java, src/test/java/org/folio/util/TestUtils.java
[MODTLR-138](https://folio-org.atlassian.net/browse/MODTLR-138)
=> MODTLR-138: Fix request update event handling

NEWS.md, pom.xml, src/main/java/org/folio/service/impl/EcsTlrServiceImpl.java, src/main/java/org/folio/service/impl/RequestEventHandler.java, src/main/java/org/folio/support/Constants.java, src/test/java/org/folio/api/EcsTlrApiTest.java, src/test/java/org/folio/service/RequestEventHandlerTest.java, src/test/java/org/folio/util/TestUtils.java
Resolves: [MODTLR-145](https://folio-org.atlassian.net/browse/MODTLR-145)
=> MODTLR-145 Release 1.0.6

src/main/java/org/folio/service/impl/StaffSlipsServiceImpl.java, src/test/java/org/folio/service/StaffSlipsServiceTest.java
[MODTLR-131](https://folio-org.atlassian.net/browse/)
TLRs in Search slips missing key tokens: **item.title field = Instance title**
=> MODTLR-131 TLRs in Search slips missing key tokens

src/main/java/org/folio/service/impl/RequestServiceImpl.java, src/test/java/org/folio/service/RequestServiceTest.java
https://folio-org.atlassian.net/browse/MODTLR-144
Update circulation_item status from PAGED to AVAILABLE when it already exists in DB. Basically this hot-fix is similar to what we already had for new circulation_item creation case.
=> MODTLR-144: Fixed ECS Request creation for available Item if Item has previously been requested, loaned, and returned.

src/main/java/org/folio/service/impl/RequestServiceImpl.java
https://folio-org.atlassian.net/browse/MODTLR-144
Fix for previous PR for same ticket
=> MODTLR-144: Fixed ECS Request creation for available Item if Item has previously been requested, loaned, and returned

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/client/feign/ConsortiaClient.java, src/main/java/org/folio/client/feign/InstanceClient.java, src/main/java/org/folio/client/feign/ItemClient.java, src/main/java/org/folio/service/ConsortiaService.java, src/main/java/org/folio/service/ConsortiumService.java, src/main/java/org/folio/service/InventoryService.java, src/main/java/org/folio/service/RequestService.java, src/main/java/org/folio/service/impl/ConsortiaServiceImpl.java, src/main/java/org/folio/service/impl/ConsortiumServiceImpl.java, src/main/java/org/folio/service/impl/InventoryServiceImpl.java, src/main/java/org/folio/service/impl/RequestServiceImpl.java, src/main/java/org/folio/service/impl/StaffSlipsServiceImpl.java, src/main/resources/permissions/mod-tlr.csv, src/main/resources/swagger.api/ecs-tlr.yaml, src/main/resources/swagger.api/schemas/consortia/common.yaml, src/main/resources/swagger.api/schemas/consortia/sharingInstance.yaml, src/main/resources/swagger.api/schemas/consortia/status.yaml, src/test/java/org/folio/api/BaseIT.java, src/test/java/org/folio/api/EcsTlrApiTest.java, src/test/java/org/folio/service/ConsortiumServiceTest.java, src/test/java/org/folio/service/RequestServiceTest.java, src/test/java/org/folio/service/StaffSlipsServiceTest.java, src/test/java/org/folio/service/impl/ConsortiaServiceTest.java
[MODTLR-148](https://folio-org.atlassian.net/browse/MODTLR-148)
=> MODTLR-148: Bugfix release 1.0.7

src/main/java/org/folio/service/impl/AllowedServicePointsForTitleLevelRequestService.java, src/main/java/org/folio/service/impl/TenantServiceImpl.java, src/test/java/org/folio/api/AllowedServicePointsApiTest.java, src/test/java/org/folio/service/TenantServiceTest.java
[_Describe the purpose of the pull request. Include background information if necessary._](https://folio-org.atlassian.net/browse/MODTLR-156)
Get tenant ID from search holdings instead of search items
=> MODTLR-156 Fix ECS TLRs for instance with holding and no items

Dockerfile, Jenkinsfile, pom.xml, src/main/java/org/folio/service/impl/CustomTenantService.java, src/test/java/org/folio/api/AllowedServicePointsApiTest.java, src/test/java/org/folio/service/BaseEventHandlerTest.java, src/test/java/org/folio/service/RequestBatchUpdateEventHandlerTest.java, src/test/java/org/folio/service/RequestServiceTest.java, src/test/java/org/folio/service/UserEventHandlerTest.java, src/test/java/org/folio/service/UserGroupEventHandlerTest.java, src/test/resources/application-test.yml, src/test/resources/mappings/users.json
https://folio-org.atlassian.net/browse/FOLREL-721
Update java and dependency versions.
=> FOLREL-721: Update to Java 21

NEWS.md, pom.xml, src/main/java/org/folio/service/impl/RequestBatchUpdateEventHandler.java, src/test/java/org/folio/service/RequestBatchUpdateEventHandlerTest.java
Resolves: [MODTLR-184](http://folio-org.atlassian.net/browse/MODTLR-184)
=> MODTLR-184 Release 1.0.10

NEWS.md, pom.xml, src/main/java/org/folio/service/impl/EcsTlrServiceImpl.java, src/main/java/org/folio/service/impl/RequestServiceImpl.java, src/test/java/org/folio/api/EcsTlrApiTest.java, src/test/java/org/folio/service/RequestServiceTest.java
[MODTLR-188](https://folio-org.atlassian.net/browse/MODTLR-188)
=> MODTLR-188: Bugfix release v1.0.11 (Ramsons R2 2024 CSP #1)

NEWS.md, pom.xml, src/main/java/org/folio/listener/kafka/KafkaEventListener.java, src/main/java/org/folio/service/impl/RequestEventHandler.java, src/main/java/org/folio/support/KafkaEvent.java, src/test/java/org/folio/listener/KafkaEventListenerTest.java, src/test/java/org/folio/service/LoanEventHandlerTest.java, src/test/java/org/folio/service/RequestEventHandlerTest.java
https://folio-org.atlassian.net/browse/MODTLR-193
=> MODTLR-193: Bugfix release 1.0.12

descriptors/ModuleDescriptor-template.json, src/main/resources/swagger.api/schemas/allowedServicePoints.yaml, src/test/java/org/folio/api/AllowedServicePointsApiTest.java
https://folio-org.atlassian.net/browse/MODTLR-202
_Describe the purpose of the pull request. Include background information if necessary._
=> MODTLR-202: Added discoveryDisplayName in AllowedServicePoints response

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/resources/swagger.api/schemas/allowedServicePoints.yaml, src/test/java/org/folio/api/AllowedServicePointsApiTest.java
https://folio-org.atlassian.net/browse/MODTLR-204
_Describe the purpose of the pull request. Include background information if necessary._
=> Ramsons (CSP#3) release 1.0.15

descriptors/ModuleDescriptor-template.json
Resolves: [MODTLR-221](https://folio-org.atlassian.net/browse/MODTLR-221)
=> MODTLR-221 Update item-storage interface version

NEWS.md, pom.xml, src/main/resources/application.yml, src/main/resources/swagger.api/schemas/circulation/check-out-dry-run-request.yaml, src/main/resources/swagger.api/schemas/circulation/check-out-request.yaml, src/test/java/org/folio/api/AllowedServicePointsApiTest.java, src/test/java/org/folio/api/CheckOutApiTest.java
Resolves: [MODTLR-250](https://folio-org.atlassian.net/browse/MODTLR-250)
=> MODTLR-250 Release 1.1.5
